.PHONY: clean All

All:
	@echo "----------Building project:[ b - Debug ]----------"
	@cd "b" && "$(MAKE)" -f  "b.mk"
clean:
	@echo "----------Cleaning project:[ b - Debug ]----------"
	@cd "b" && "$(MAKE)" -f  "b.mk" clean
